fix revive issues
In golangci-lint and upstream, revive has replaced golint because golint is no
longer maintained. revive finds some more issues that need to be fixed before
it can be used:

    ktesting/testinglogger.go:81:20: unused-parameter: parameter 'args' seems to be unused, consider removing or renaming it as _ (revive)
    func (n NopTL) Log(args ...interface{}) {}
                       ^
    klogr/klogr_test.go:23:2: redefines-builtin-id: redefinition of the built-in function new (revive)
    	new := func() logr.Logger {
    		switch format {
    		case formatNew:
    			return New()
    		case formatDefault:
    			return NewWithOptions()
    		default:
    			return NewWithOptions(WithFormat(Format(format)))
    		}
    	}
    internal/clock/testing/fake_clock.go:261:29: unused-parameter: parameter 'd' seems to be unused, consider removing or renaming it as _ (revive)
    func (*IntervalClock) After(d time.Duration) <-chan time.Time {
                                ^
    internal/clock/testing/fake_clock.go:267:32: unused-parameter: parameter 'd' seems to be unused, consider removing or renaming it as _ (revive)
    func (*IntervalClock) NewTimer(d time.Duration) clock.Timer {
                                   ^
    internal/clock/testing/fake_clock.go:273:33: unused-parameter: parameter 'd' seems to be unused, consider removing or renaming it as _ (revive)
    func (*IntervalClock) AfterFunc(d time.Duration, f func()) clock.Timer {
                                    ^
    textlogger/textlogger.go:148:2: redefines-builtin-id: redefinition of the built-in function new (revive)
    	new := *l
    	^
    textlogger/textlogger.go:157:2: redefines-builtin-id: redefinition of the built-in function new (revive)
    	new := *l
    	^
    textlogger/textlogger.go:91:24: unused-parameter: parameter 'level' seems to be unused, consider removing or renaming it as _ (revive)
    func (l *tlogger) Info(level int, msg string, kvList ...interface{}) {
                           ^
    klog_test.go:2204:2: redefines-builtin-id: redefinition of the built-in function copy (revive)
    	copy := settings.deepCopy()
    	^
    klog_test.go:95:48: unused-parameter: parameter 't' seems to be unused, consider removing or renaming it as _ (revive)
    func contains(s severity.Severity, str string, t *testing.T) bool {
                                                   ^
    klog_test.go:378:28: unused-parameter: parameter 't' seems to be unused, consider removing or renaming it as _ (revive)
    func TestSetOutputDataRace(t *testing.T) {
                               ^
    klog_test.go:1807:25: unused-parameter: parameter 'level' seems to be unused, consider removing or renaming it as _ (revive)
    func (l *testLogr) Info(level int, msg string, keysAndValues ...interface{}) {
                            ^
    klog_test.go:1828:25: unused-parameter: parameter 'info' seems to be unused, consider removing or renaming it as _ (revive)
    func (l *testLogr) Init(info logr.RuntimeInfo)             {}
                            ^
    klog_test.go:1829:28: unused-parameter: parameter 'level' seems to be unused, consider removing or renaming it as _ (revive)
    func (l *testLogr) Enabled(level int) bool                 { return true }
                               ^
    klog_test.go:1833:34: unused-parameter: parameter 'depth' seems to be unused, consider removing or renaming it as _ (revive)
    func (l *testLogr) WithCallDepth(depth int) logr.LogSink   { return l }
                                     ^